In [118]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
df = pd.read_csv('homeprice_banglore.csv')
df.head(5)

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [119]:
from sklearn import preprocessing

sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

# scaled_x = sx.fit_transform(df.drop('price', axis=1))

# scaled_x[:5]

In [120]:
df['price']

0      39.07
1     120.00
2      62.00
3      75.00
4      51.00
5      38.00
6     135.00
7     155.00
8      50.00
9     167.00
10     82.00
11    140.00
12     38.00
13     40.00
14    101.00
15     42.00
16     48.00
17     60.00
18    102.00
19     32.00
Name: price, dtype: float64

In [121]:
scaled_y = sy.fit_transform(df[['price']].values.reshape(df.shape[0], 1))
scaled_y[:5]
# scaled_y = sy.fit_transform(df[['price']])
# scaled_y[:5]

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074]])

In [122]:
scaled_y.reshape(scaled_y.shape[0],)

array([0.05237037, 0.65185185, 0.22222222, 0.31851852, 0.14074074,
       0.04444444, 0.76296296, 0.91111111, 0.13333333, 1.        ,
       0.37037037, 0.8       , 0.04444444, 0.05925926, 0.51111111,
       0.07407407, 0.11851852, 0.20740741, 0.51851852, 0.        ])

In [123]:
# scaled_y.reshape(scaled_y.shape[0],)
scaled_x = df.drop('price', axis=1)
y = df['price']

In [124]:
scaled_x

area  bedrooms
0   1056         2
1   2600         4
2   1440         3
3   1521         3
4   1200         2
5   1170         2
6   2732         4
7   3300         4
8   1310         3
9   3700         5
10  1800         3
11  2785         4
12  1000         2
13  1100         2
14  2250         3
15  1175         2
16  1180         3
17  1540         3
18  2770         3
19   800         1

In [125]:
scaled_x.T

0     1     2     3     4     5     6     7     8     9     10  \
area      1056  2600  1440  1521  1200  1170  2732  3300  1310  3700  1800   
bedrooms     2     4     3     3     2     2     4     4     3     5     3   

            11    12    13    14    15    16    17    18   19  
area      2785  1000  1100  2250  1175  1180  1540  2770  800  
bedrooms     4     2     2     3     2     3     3     3    1

In [126]:
scaled_x.T.shape

(2, 20)

In [127]:
w = np.ones(shape=(scaled_x.shape[1]))
w.shape

(2,)

In [128]:
p = np.dot(w, scaled_x.T)+2.2
p

array([1060.2, 2606.2, 1445.2, 1526.2, 1204.2, 1174.2, 2738.2, 3306.2,
       1315.2, 3707.2, 1805.2, 2791.2, 1004.2, 1104.2, 2255.2, 1179.2,
       1185.2, 1545.2, 2775.2,  803.2])

In [129]:
p.shape

(20,)

In [130]:
scaled_x.T.dot(p)

area        80757197.8
bedrooms      120116.6
dtype: float64

In [131]:
np.dot(scaled_x.T, p)

array([80757197.8,   120116.6])

---


In [132]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [133]:
df = pd.read_csv("insurace_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [134]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df[['age', 'affordibility']], df['bought_insurance'], test_size=0.2, random_state=25)

In [135]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
def log_loss(y_true, y_pred):
    # Small epsilon to avoid log(0)
    epsilon = 1e-15

    # Step 1: Clip y_pred values to avoid log(0) issues
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    print("Clipped y_pred:", y_pred)

    # Step 2: Calculate log(y_pred) and log(1 - y_pred)
    log_y_pred = np.log(y_pred)
    log_one_minus_y_pred = np.log(1 - y_pred)
    print("log(y_pred):", log_y_pred)
    print("log(1 - y_pred):", log_one_minus_y_pred)

    # Step 3: Calculate y_true * log(y_pred)
    term1 = y_true * log_y_pred 
    print("y_true * log(y_pred):", term1)

    # Step 4: Calculate (1 - y_true) * log(1 - y_pred)
    term2 = (1 - y_true) * log_one_minus_y_pred
    print("(1 - y_true) * log(1 - y_pred):", term2)

    # Step 5: Combine terms and calculate mean
    log_loss_value = -np.mean(term1 + term2)
    print("Log Loss Value:", log_loss_value)

    return log_loss_value

In [137]:
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))

0 0.577713
13 0.395549
6 0.456622
17 0.659188
24 0.641694
19 0.568299
25 0.650492
16 0.386388
20 0.575365
3 0.449471
7 0.468578
1 0.386388
5 0.654853
27 0.632800
8 0.667778
18 0.372797
12 0.390959
23 0.630562
22 0.619290
15 0.652675
26 0.580058
4 0.632800
dtype: float64


In [138]:
class myNeuralNetwork:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0

    def fit(self, X, y, epochs, loss_threshold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_threshold)

    def predict(self, X_test):
        weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_threshold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(X_train)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordibility + bias
            y_predicted = sigmoid_numpy(weighted_sum)

            loss = log_loss(y_true, y_predicted)

            w1d = (1 / n) * np.dot(np.transpose(age), (y_predicted - y_true))
            w2d = (1 / n) * np.dot(np.transpose(affordibility), (y_predicted - y_true))

            bias_d = np.mean(y_predicted - y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d

            if i % 50 == 0:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

            if loss <= loss_threshold:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break
        return w1, w2, bias

In [ ]:
customModel = myNeuralNetwork()
customModel.fit(X_train_scaled, y_train, 1000, 0.4631)

Clipped y_pred: 0     0.772064
13    0.571996
6     0.634136
17    0.829205
24    0.817574
19    0.764948
25    0.823465
16    0.562177
20    0.770299
3     0.627148
7     0.645656
1     0.562177
5     0.826353
27    0.811533
8     0.834795
18    0.547358
12    0.567093
23    0.809998
22    0.802184
15    0.824914
26    0.773819
4     0.811533
dtype: float64
log(y_pred): 0    -0.258688
13   -0.558623
6    -0.455492
17   -0.187288
24   -0.201413
19   -0.267948
25   -0.194235
16   -0.575939
20   -0.260977
3    -0.466573
7    -0.437488
1    -0.575939
5    -0.190733
27   -0.208831
8    -0.180569
18   -0.602653
12   -0.567232
23   -0.210723
22   -0.220417
15   -0.192476
26   -0.256418
4    -0.208831
dtype: float64
log(1 - y_pred): 0    -1.478688
13   -0.848623
6    -1.005492
17   -1.767288
24   -1.701413
19   -1.447948
25   -1.734235
16   -0.825939
20   -1.470977
3    -0.986573
7    -1.037488
1    -0.825939
5    -1.750733
27   -1.668831
8    -1.800569
18   -0.792653
12   -0.837232
23   -1.6

Traceback (most recent call last):
  File "c:\Users\91630\.conda\envs\ml_env\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 622, in change_attr_expression
    value = eval(expression, frame.f_globals, frame.f_locals)
  File "<string>", line 1
    0     0.77206413    0.5719966     0.63413617    0.82920524    0.81757419    0.76494825    0.82346516    0.56217720    0.7702993     0.6271487     0.6456561     0.5621775     0.82635327    0.8115338     0.83479518    0.54735812    0.56709323    0.80999822    0.80218415    0.82491426    0.7738194     0.811533dtype: float64
          ^
SyntaxError: invalid syntax


In [140]:
customModel.predict(X_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64